<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SetsOfCriteriasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('sets_of_criterias')->delete();

        DB::table('sets_of_criterias')->insert(
            [
                [
                    'id' => 1,
                    'criteria_id' => 1,
                    'member_names' => 'Membosankan',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 2,
                    'criteria_id' => 1,
                    'member_names' => 'Kurang Menyenangkan',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 3,
                    'criteria_id' => 1,
                    'member_names' => 'Menyenangkan',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 4,
                    'criteria_id' => 1,
                    'member_names' => 'Lebih Menyenangkan',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 5,
                    'criteria_id' => 1,
                    'member_names' => 'Sangat Menyenangkan',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 6,
                    'criteria_id' => 2,
                    'member_names' => 'Tidak Jelas',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 7,
                    'criteria_id' => 2,
                    'member_names' => 'Kurang Jelas',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 8,
                    'criteria_id' => 2,
                    'member_names' => 'Jelas',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 9,
                    'criteria_id' => 2,
                    'member_names' => 'Lebih Jelas',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 10,
                    'criteria_id' => 2,
                    'member_names' => 'Sangat Jelas',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 11,
                    'criteria_id' => 3,
                    'member_names' => 'Tidak Kekinian',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 12,
                    'criteria_id' => 3,
                    'member_names' => 'Kurang Kekinian',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 13,
                    'criteria_id' => 3,
                    'member_names' => 'Kekinian',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 14,
                    'criteria_id' => 3,
                    'member_names' => 'Lebih Kekinian',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 15,
                    'criteria_id' => 3,
                    'member_names' => 'Sangat Kekinian',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 16,
                    'criteria_id' => 4,
                    'member_names' => 'Tidak Memotivasi',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 17,
                    'criteria_id' => 4,
                    'member_names' => 'Kurang Memotivasi',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 18,
                    'criteria_id' => 4,
                    'member_names' => 'Memotivasi',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 19,
                    'criteria_id' => 4,
                    'member_names' => 'Lebih Memotivasi',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 20,
                    'criteria_id' => 4,
                    'member_names' => 'Sangat Memotivasi',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 21,
                    'criteria_id' => 5,
                    'member_names' => '1',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 22,
                    'criteria_id' => 5,
                    'member_names' => '2',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 23,
                    'criteria_id' => 5,
                    'member_names' => '3',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 24,
                    'criteria_id' => 5,
                    'member_names' => '4',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 25,
                    'criteria_id' => 5,
                    'member_names' => '5',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 26,
                    'criteria_id' => 5,
                    'member_names' => '6',
                    'member_value' => 6,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 27,
                    'criteria_id' => 5,
                    'member_names' => '7',
                    'member_value' => 7,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 28,
                    'criteria_id' => 5,
                    'member_names' => '8',
                    'member_value' => 8,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 29,
                    'criteria_id' => 5,
                    'member_names' => '9',
                    'member_value' => 9,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 30,
                    'criteria_id' => 5,
                    'member_names' => '10',
                    'member_value' => 10,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 31,
                    'criteria_id' => 6,
                    'member_names' => 'Tidak Ramah',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 32,
                    'criteria_id' => 6,
                    'member_names' => 'Kurang Ramah',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 33,
                    'criteria_id' => 6,
                    'member_names' => 'Ramah',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 34,
                    'criteria_id' => 6,
                    'member_names' => 'Lebih Ramah',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 35,
                    'criteria_id' => 6,
                    'member_names' => 'Sangat Ramah',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 36,
                    'criteria_id' => 7,
                    'member_names' => 'Tidak Berdiskusi',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 37,
                    'criteria_id' => 7,
                    'member_names' => 'Sulit Berdiskusi',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 38,
                    'criteria_id' => 7,
                    'member_names' => 'Berdiskusi',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 39,
                    'criteria_id' => 7,
                    'member_names' => 'Mudah Berdiskusi',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 40,
                    'criteria_id' => 7,
                    'member_names' => 'Sangat Mudah Berdiskusi',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 41,
                    'criteria_id' => 8,
                    'member_names' => '1',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 42,
                    'criteria_id' => 8,
                    'member_names' => '2',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 43,
                    'criteria_id' => 8,
                    'member_names' => '3',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 44,
                    'criteria_id' => 8,
                    'member_names' => '4',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 45,
                    'criteria_id' => 8,
                    'member_names' => '5',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 46,
                    'criteria_id' => 8,
                    'member_names' => '6',
                    'member_value' => 6,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 47,
                    'criteria_id' => 8,
                    'member_names' => '7',
                    'member_value' => 7,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 48,
                    'criteria_id' => 8,
                    'member_names' => '8',
                    'member_value' => 8,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 49,
                    'criteria_id' => 8,
                    'member_names' => '9',
                    'member_value' => 9,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 50,
                    'criteria_id' => 8,
                    'member_names' => '10',
                    'member_value' => 10,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 51,
                    'criteria_id' => 9,
                    'member_names' => '1',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 52,
                    'criteria_id' => 9,
                    'member_names' => '2',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 53,
                    'criteria_id' => 9,
                    'member_names' => '3',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 54,
                    'criteria_id' => 9,
                    'member_names' => '4',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 55,
                    'criteria_id' => 9,
                    'member_names' => '5',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 56,
                    'criteria_id' => 9,
                    'member_names' => '6',
                    'member_value' => 6,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 57,
                    'criteria_id' => 9,
                    'member_names' => '7',
                    'member_value' => 7,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 58,
                    'criteria_id' => 9,
                    'member_names' => '8',
                    'member_value' => 8,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 59,
                    'criteria_id' => 9,
                    'member_names' => '9',
                    'member_value' => 9,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 60,
                    'criteria_id' => 9,
                    'member_names' => '10',
                    'member_value' => 10,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 61,
                    'criteria_id' => 10,
                    'member_names' => 'Tidak Peduli',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 62,
                    'criteria_id' => 10,
                    'member_names' => 'Kurang Peduli',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 63,
                    'criteria_id' => 10,
                    'member_names' => 'Peduli',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 64,
                    'criteria_id' => 10,
                    'member_names' => 'Lebih Peduli',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 65,
                    'criteria_id' => 10,
                    'member_names' => 'Sangat Peduli',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 66,
                    'criteria_id' => 11,
                    'member_names' => 'Sulit Ditemui',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 67,
                    'criteria_id' => 11,
                    'member_names' => 'Cukup Sulit Ditemui',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 68,
                    'criteria_id' => 11,
                    'member_names' => 'Mudah Ditemui',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 69,
                    'criteria_id' => 11,
                    'member_names' => 'Lebih Mudah Ditemui',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 70,
                    'criteria_id' => 11,
                    'member_names' => 'Sangat Mudah Ditemui',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 71,
                    'criteria_id' => 12,
                    'member_names' => 'Tidak Pernah',
                    'member_value' => 1,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 72,
                    'criteria_id' => 12,
                    'member_names' => 'Kurang',
                    'member_value' => 2,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 73,
                    'criteria_id' => 12,
                    'member_names' => 'Kadang-Kadang',
                    'member_value' => 3,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 74,
                    'criteria_id' => 12,
                    'member_names' => 'Sering',
                    'member_value' => 4,
                    'created_at' => Carbon::now(),
                ],
                [
                    'id' => 75,
                    'criteria_id' => 12,
                    'member_names' => 'Selalu',
                    'member_value' => 5,
                    'created_at' => Carbon::now(),
                ],
            ]
        );
    }
}
